# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RationBalancing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RationBalancing

  target 'RationBalancingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RationBalancingUITests' do
    # Pods for testing
  end
	pod 'Backendless'
end
